//Problem 2

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms


module SumOfEvenFibonacciNumbers

    let sumOfFibonacciEvenTermsUpto4Million = 
        Seq.unfold (fun state -> 
            if (snd state > 4000000) then None      //TODO : hard-coded value 4 million
            else Some(fst state + snd state, (snd state, fst state + snd state))) (1,2)
            |> Seq.filter(fun term -> term % 2 = 0)
            |> Seq.sum